/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as FeedingRouteImport } from './routes/feeding'
import { Route as IotRouteImport } from './routes/iot'
import { Route as AnimalsIndexRouteImport } from './routes/animals.index'
import { Route as AnimalsIdRouteImport } from './routes/animals.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedingRoute = FeedingRouteImport.update({
  id: '/feeding',
  path: '/feeding',
  getParentRoute: () => rootRouteImport,
} as any)
const IotRoute = IotRouteImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsIndexRoute = AnimalsIndexRouteImport.update({
  id: '/animals/',
  path: '/animals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsIdRoute = AnimalsIdRouteImport.update({
  id: '/animals/$id',
  path: '/animals/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/feeding': typeof FeedingRoute
  '/iot': typeof IotRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/animals/': typeof AnimalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/feeding': typeof FeedingRoute
  '/iot': typeof IotRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/animals': typeof AnimalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/feeding': typeof FeedingRoute
  '/iot': typeof IotRoute
  '/animals/$id': typeof AnimalsIdRoute
  '/animals/': typeof AnimalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/alerts' | '/feeding' | '/iot' | '/animals/$id' | '/animals/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alerts' | '/feeding' | '/iot' | '/animals/$id' | '/animals'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/feeding'
    | '/iot'
    | '/animals/$id'
    | '/animals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  FeedingRoute: typeof FeedingRoute
  IotRoute: typeof IotRoute
  AnimalsIdRoute: typeof AnimalsIdRoute
  AnimalsIndexRoute: typeof AnimalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeding': {
      id: '/feeding'
      path: '/feeding'
      fullPath: '/feeding'
      preLoaderRoute: typeof FeedingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iot': {
      id: '/iot'
      path: '/iot'
      fullPath: '/iot'
      preLoaderRoute: typeof IotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/': {
      id: '/animals/'
      path: '/animals'
      fullPath: '/animals/'
      preLoaderRoute: typeof AnimalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/$id': {
      id: '/animals/$id'
      path: '/animals/$id'
      fullPath: '/animals/$id'
      preLoaderRoute: typeof AnimalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  FeedingRoute: FeedingRoute,
  IotRoute: IotRoute,
  AnimalsIdRoute: AnimalsIdRoute,
  AnimalsIndexRoute: AnimalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
